import UserProfile from "@/components/UserProfile";
import type { Metadata } from "next";

import styles from "./Layout.module.css";

export const metadata: Metadata = {
  title: "Quiz",
  description: "Generated by Next.js and Django!",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className={styles.mainContainer}>
      <UserProfile />
      {children}
    </main>
  );
}
