import type { Metadata } from "next";

import { QuizUserProvider } from "@/context/QuizUserContext";
import "@styles/globals.css";

export const metadata: Metadata = {
  title: "Quiz",
  description: "Generated by Next.js and Django!",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className="main">
        <QuizUserProvider>{children}</QuizUserProvider>
      </body>
    </html>
  );
}
