# version: "3.9"

services:
  web:
    image: web
    container_name: web
    build:
      context: ./web
    restart: always
    volumes:
      - ./web:/usr/src/app
      - /web/app/node_modules
    env_file:
      - ./web/.env.local
    ports:
      - 3000:3000
    networks:
      - quiz_network

  api:
    image: api
    container_name: api
    build:
      context: ./api
    restart: always
    volumes:
      - ./api/api-django:/api
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./api/dot_env/.env
    depends_on:
      - quiz_db
    ports:
      - 8000:8000
    networks:
      - quiz_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    env_file:
      - ./api/dot_env/.env
    depends_on:
      - quiz_db
    ports:
      - 5050:80
    networks:
      - quiz_network

  quiz_db:
    image: postgres:16.1-alpine3.19
    container_name: quiz_db
    volumes:
      - ./data/postgres/api:/var/lib/postgresql/data/
    env_file:
      - ./api/dot_env/.env
    ports:
      - 5432:5432
    networks:
      - quiz_network

networks:
  quiz_network:
    driver: bridge
