# Generated by Django 4.2.4 on 2023-09-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
