# Generated by Django 4.2.4 on 2023-09-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_quizuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='total_correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
