# Generated by Django 4.2.4 on 2023-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_quizuser_total_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
