import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Body from "../components/Body";
import { UserProvider } from "../contexts/userContext";
import { ModalProvider } from "../contexts/modalContext";
import { DarkModeProvider } from "../contexts/darkModeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <ModalProvider>
          <UserProvider>
            <Body fontFamily={inter.className}>{children}</Body>
          </UserProvider>
        </ModalProvider>
      </DarkModeProvider>
    </html>
  );
}
