### --------------------========== Quiz ==========--------------------
### Read all quiz
GET http://127.0.0.1:8000/api/quiz

### Read a single quiz
GET http://127.0.0.1:8000/api/quiz/2

### Create quiz
POST http://127.0.0.1:8000/api/quiz/
Content-Type: application/json

{
    "subject": "História do Brasil"
}

### Update quiz
PUT http://127.0.0.1:8000/api/quiz/5
Content-Type: application/json

{
    "subject": "Geometria Analítica"
}

### Delete quiz
DELETE http://127.0.0.1:8000/api/quiz/18

### --------------------========== Question ==========--------------------
### Read 10 random questions (any quiz)
GET http://127.0.0.1:8000/api/quiz/question

### Read 2 random questions (any quiz)
GET http://127.0.0.1:8000/api/quiz/question?size=2

### Read 10 random questions from quiz_id=2
GET http://127.0.0.1:8000/api/quiz/question?quiz=5

### Read 10 random questions from specific quiz list ids (id=1, id=2)
GET http://127.0.0.1:8000/api/quiz/question?quiz=1&quiz=2

### Read 2 random questions from specific quiz list ids (id=1, id=2)
GET http://127.0.0.1:8000/api/quiz/question?quiz=1&quiz=2&size=2

### Read 1 random question based on its id
GET http://127.0.0.1:8000/api/quiz/question/66

### Create question
POST http://127.0.0.1:8000/api/quiz/question
Content-Type: application/json

{
    "quiz_id": 5,
    "question_text": "Essa questão é um teste"
}

### Update question
PUT http://127.0.0.1:8000/api/quiz/question/64
Content-Type: application/json

{
    "quiz_id": 3,
    "question_text": "Essa questão é outro teste"
}

### Delete question
DELETE http://127.0.0.1:8000/api/quiz/question/64

### --------------------========== Answer ==========--------------------
### Read a single answer
# GET http://127.0.0.1:8000/api/quiz/answer/2

### Create set of answers
POST http://127.0.0.1:8000/api/quiz/answer
Content-Type: application/json

{
    "question_id": 66,
    "answers": [
        {
            "text": "Alternativa 1"
        },
        {
            "text": "Alternativa 2"
        },
        {
            "text": "Alternativa 3"
        },
        {
            "text": "Alternativa 4"
        }
    ]
}

### Update answer
PUT http://127.0.0.1:8000/api/quiz/answer
Content-Type: application/json

{
    "question_id": 66,
    "answers": [
        {
            "pk": 269,
            "text": "Nova alternativa 1"
        },
        {
            "pk": 270,
            "text": "Nova alternativa 2"
        },
        {
            "pk": 271,
            "text": "Nova alternativa 3"
        },
        {
            "pk": 272,
            "text": "Nova alternativa 4"
        }
    ]
}

### --------------------========== User ==========--------------------
### List user
GET http://127.0.0.1:8000/api/user/list
Content-Type: application/json

### Register user
POST http://127.0.0.1:8000/api/user/register
Content-Type: application/json

{
    "username": "johndoe",
    "password": "P@ssw0rd"
}

### Login user
POST http://127.0.0.1:8000/api/user/token-access
Content-Type: application/json

{
    "username": "johndoe",
    "password": "P@ssw0rd"
}

### Refresh user (refresh token)
POST http://127.0.0.1:8000/api/user/token-refresh
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxODkxMjg0NSwiaWF0IjoxNzE4MzA4MDQ1LCJqdGkiOiJjNDAxNjU1ZTgwMjA0MTg0OWVlM2Y1MTM3OTUzNDg2YiIsInVzZXJfaWQiOjF9.p9RIEoilT5Lu0u_njrEtvpr1a48Y3zEKfq5XMw7jBig"
}

### Verify user (access token) -> HTTP 200
POST http://127.0.0.1:8000/api/user/token-verify
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MzExNjQ1LCJpYXQiOjE3MTgzMDgwNDUsImp0aSI6IjJjMTQ5NGFlYmYyZjRkYmQ4NWU1NWQ3NzFiODE5YzI3IiwidXNlcl9pZCI6MX0.5fRTqrlvn3_cY7ToUNAhLdMlGUHn3ddu7mB7IS87ryA"
}

### Get user data (access token)
GET http://127.0.0.1:8000/api/user/get-data
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MzExNjQ1LCJpYXQiOjE3MTgzMDgwNDUsImp0aSI6IjJjMTQ5NGFlYmYyZjRkYmQ4NWU1NWQ3NzFiODE5YzI3IiwidXNlcl9pZCI6MX0.5fRTqrlvn3_cY7ToUNAhLdMlGUHn3ddu7mB7IS87ryA

### Update user (access token)
PUT http://127.0.0.1:8000/api/user/update
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MzExNjQ1LCJpYXQiOjE3MTgzMDgwNDUsImp0aSI6IjJjMTQ5NGFlYmYyZjRkYmQ4NWU1NWQ3NzFiODE5YzI3IiwidXNlcl9pZCI6MX0.5fRTqrlvn3_cY7ToUNAhLdMlGUHn3ddu7mB7IS87ryA

# Username only
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{
    "username": "abi"
}

# Avatar only
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="1.png"
Content-Type: image/png

--boundary
Content-Disposition: form-data; name="avatar"
Content-Type: image/jpg

### Delete user
DELETE http://127.0.0.1:8000/api/user/delete
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MzExNjQ1LCJpYXQiOjE3MTgzMDgwNDUsImp0aSI6IjJjMTQ5NGFlYmYyZjRkYmQ4NWU1NWQ3NzFiODE5YzI3IiwidXNlcl9pZCI6MX0.5fRTqrlvn3_cY7ToUNAhLdMlGUHn3ddu7mB7IS87ryA

### --------------------========== Score ==========--------------------
### List scores
GET http://127.0.0.1:8000/api/user/list-scores
Content-Type: application/json

### Complete quiz
POST http://127.0.0.1:8000/api/user/complete-quiz
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4MzExNjQ1LCJpYXQiOjE3MTgzMDgwNDUsImp0aSI6IjJjMTQ5NGFlYmYyZjRkYmQ4NWU1NWQ3NzFiODE5YzI3IiwidXNlcl9pZCI6MX0.5fRTqrlvn3_cY7ToUNAhLdMlGUHn3ddu7mB7IS87ryA

{
    "quiz": [
        {
            "quizId": 1, 
            "totalQuestions": 9, 
            "correctAnswers": 8
        }, 
        {
            "quizId": 2, 
            "totalQuestions": 11, 
            "correctAnswers": 7
        } 
    ]
}





